In [98]:
import numpy as np

import random

from sympy.codegen.fnodes import dimension

In [5]:
# Generate the 2d arrays
arr=np.random.rand(3,3)
print(arr)

[[0.02379972 0.14806624 0.41800119]
 [0.05606735 0.84682607 0.52649766]
 [0.32739949 0.51640788 0.74637722]]


In [8]:
np.max(arr,axis=0)

array([0.32739949, 0.84682607, 0.74637722])

In [10]:
# Create a 2D array
arr_2d = np.array([[1, 89, 3],
                   [4, 5, 6]])

# Max along axis 0 (columns)
max_axis0 = np.max(arr_2d, axis=0)  # [4, 5, 6]
# Max along axis 1 (rows)
max_axis1 = np.max(arr_2d, axis=1)  # [3, 6]

print("Max along axis 0:", max_axis0)
print("Max along axis 1:", max_axis1)

Max along axis 0: [ 4 89  6]
Max along axis 1: [89  6]


In [13]:
mean=np.mean(arr_2d, axis=0)[0]
mean

2.5

Weighted mean

In [22]:
data=np.linspace(0,10,6)
print(data)
weights=np.random.rand(6)
print(weights)
weighted_sum=np.average(data,weights=weights)
print(weighted_sum)

[ 0.  2.  4.  6.  8. 10.]
[0.21526412 0.35124445 0.83287194 0.48523825 0.27357729 0.63016582]
5.535753031826085


In [25]:
arr=np.linspace(0,10,6)
arr

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [29]:
import numpy as np

# Step 1: Create a population (e.g., 10000 people with random ages)
np.random.seed(42)  # for reproducibility
population = np.random.normal(loc=35, scale=10, size=10000)  # mean=35, std=10

# Step 2: Take a random sample (e.g., 200 people)
sample = np.random.choice(population, size=200, replace=False)

# Step 3: Calculate population mean (μ) and sample mean (x̄)
population_mean = np.mean(population)
sample_mean = np.mean(sample)

print(f"Population Mean (μ): {population_mean:.2f}")
print(f"Sample Mean (x̄): {sample_mean:.2f}")


Population Mean (μ): 34.98
Sample Mean (x̄): 36.06


You're absolutely right. In **NumPy**, the function `np.std()` includes the `ddof` (delta degrees of freedom) parameter, which directly controls whether you're computing the **population** or **sample** standard deviation.

Here's a breakdown:

---

### 📌 **NumPy `np.std()` Parameters Relevant to Standard Deviation**

```python
numpy.std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>)
```

---

### 🔑 **Key Parameter: `ddof` (Degrees of Freedom)**

* **`ddof=0`** (default):

  * Calculates **population standard deviation**
  * Divides by **N**
  * Formula:

    $$
    \sigma = \sqrt{\frac{1}{N} \sum_{i=1}^{N} (x_i - \mu)^2}
    $$

* **`ddof=1`**:

  * Calculates **sample standard deviation**
  * Divides by **N - 1** (Bessel’s correction)
  * Formula:

    $$
    s = \sqrt{\frac{1}{n - 1} \sum_{i=1}^{n} (x_i - \bar{x})^2}
    $$

---

### ✅ Example in Code


---

### ⚠️ Common Mistake

* Forgetting to set `ddof=1` when working with **sample data**, leading to **underestimated variance**.

---

Let me know if you want this done in **Pandas**, or if you're comparing it with other tools like Excel, R, or SciPy.


In [35]:
arr=np.random.rand(4)
exponential_values=np.exp(arr)
print(exponential_values)

[1.16884799 1.1688198  1.0598036  2.37780108]


In [37]:
import numpy as np

# 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(arr_2d[1,0])
print(arr_2d[1,])


4
[4 5 6]


In [41]:
arr=np.linspace(0,10,6)
print(arr)
n=arr>2
print(n)
arr[n]


[ 0.  2.  4.  6.  8. 10.]
[False False  True  True  True  True]


array([ 4.,  6.,  8., 10.])

In [42]:
import numpy as np

# create a numpy array
numbers = np.array([2, 4, 6, 8, 10, 12])

# slice the last 3 elements of the array
# using the start parameter
print(numbers[-3:])    # [8 10 12]

# slice elements from 2nd-to-last to 4th-to-last element
# using the start and stop parameters
print(numbers[-5:-2])    # [4 6 8]

# slice every other element of the array from the end
# using the start, stop, and step parameters
print(numbers[-1::-2])   # [12 8 4]

[ 8 10 12]
[4 6 8]
[12  8  4]


2d array slicing
Views vs. Copies: Slicing creates a view, but fancy indexing or boolean indexing creates a copy.



In [44]:
import numpy as np

# create a 2D array
array1 = np.array([[1, 3, 5, 7],
                      [9, 11, 13, 15],
                      [2, 4, 6, 8]])

print(array1[1:3,2:4])

[[13 15]
 [ 6  8]]


FANCY INDEXING

In [46]:
arr2d = np.array([[10, 20],
                  [30, 40],
                  [50, 60]])

rows = [0, 1, 2]
cols = [0]

print(arr2d[rows, cols])  # Output: [20 30 60]


[10 30 50]


In [49]:
rows = [0]
cols = [0,1]

print(arr2d[rows, cols])

[10 20]


In [52]:
rows = [0,2]
cols = [1,0]

print(arr2d[rows, cols])

[20 50]


In [56]:
arr_2d = np.array([[1, 2], [3, 4]])
print(arr_2d)
for i in np.nditer(arr_2d):#in flattend way
    print(i)

[[1 2]
 [3 4]]
1
2
3
4


Reshape (np.reshape): Changes the shape of an array (e.g., from 1D to 2D).


Transpose (np.transpose or .T): Swaps axes (e.g., rows become columns).


Ravel (np.ravel): Flattens a multi-dimensional array into a 1D array.

In [65]:
arr=np.arange(1,10)
print("original array: ",arr)
reshaped=arr.reshape(3,3)
reshaped

original array:  [1 2 3 4 5 6 7 8 9]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
transpose=reshaped.T
transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [67]:
np.ravel(transpose)

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [70]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, -1)  # Infers 3 columns ie numpy figures out internally
print("Reshaped with -1:\n", reshaped)  # [[1, 2, 3], [4, 5, 6]]

Reshaped with -1:
 [[1 2 3]
 [4 5 6]]


In [89]:
arr_3d=np.array(
[
  [ [1, 2], [3, 4] ],   # Block 0
  [ [5, 6], [7, 8] ]    # Block 1
]
)

arr_3d.shape

(2, 2, 2)

In [87]:
arr_3d[0]

array([[1, 2],
       [3, 4]])

vstack (np.vstack): Stacks arrays vertically (row-wise, along axis 0).
hstack (np.hstack): Stacks arrays horizontally (column-wise, along axis 1).

In [91]:
# Create two arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Vertical stacking
v_stack = np.vstack((a, b))
v_stack

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [92]:
h_stack=np.hstack((a, b))
h_stack

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [94]:
a = np.array([1, 2])
b = np.array([3, 4])
v_stack = np.vstack((a, b))  # [[1, 2], [3, 4]]
h_stack = np.hstack((a, b))  # [1, 2, 3, 4]
print("vstack 1D:\n", v_stack)
print("hstack 1D:", h_stack)

vstack 1D:
 [[1 2]
 [3 4]]
hstack 1D: [1 2 3 4]


5. Splitting - hsplit, vsplit
Splitting divides an array into multiple smaller arrays along a specified axis.

Basics
hsplit (np.hsplit): Splits an array horizontally (column-wise, along axis 1).
vsplit (np.vsplit): Splits an array vertically (row-wise, along axis 0).

In [102]:
import numpy as np

# Create a 2D array (3 rows and 6 columns)
arr = np.array([[1, 2, 3, 4, 5, 6],
                [7, 8, 9, 10, 11, 12],
                [13, 14, 15, 16, 17, 18]])

# Split the array into 3 sub-arrays along axis=1 (columns)
split_arr = np.hsplit(arr, 3)

print(split_arr)


# The array was split into 3 sub-arrays along the horizontal axis (i.e., columns).

[array([[ 1,  2],
       [ 7,  8],
       [13, 14]]), array([[ 3,  4],
       [ 9, 10],
       [15, 16]]), array([[ 5,  6],
       [11, 12],
       [17, 18]])]


In [103]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Split the array into 3 sub-arrays along axis=0 (rows)
split_arr = np.vsplit(arr, 3)

print(split_arr)


[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]
