In [13]:
import numpy as np

import random

In [14]:
# Generate the 2d arrays
arr=np.random.rand(3,3)
print(arr)

[[0.66918209 0.25409658 0.46696694]
 [0.6214499  0.3452359  0.79601439]
 [0.58337049 0.43760668 0.59643536]]
